name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Setup Node
      uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
